// <auto-generated />
using System;
using GestionEquipo.DB.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEquipo.DB.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241007020320_DBControllers")]
    partial class DBControllers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.AsistEntrenamiento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Asistio")
                        .HasColumnType("bit");

                    b.Property<int>("EntrenamientoID")
                        .HasColumnType("int");

                    b.Property<int>("JugadorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EntrenamientoID");

                    b.HasIndex(new[] { "JugadorID", "EntrenamientoID" }, "AsistEntrenamiento_UQ")
                        .IsUnique();

                    b.ToTable("AsistEntrenamientos");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.Entrenamiento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.EstPartido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<int>("JugadorID")
                        .HasColumnType("int");

                    b.Property<int>("MinutosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PartidoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PartidoID");

                    b.HasIndex(new[] { "JugadorID", "PartidoID" }, "EstPartido_UQ")
                        .IsUnique();

                    b.ToTable("EstPartidos");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.Jugador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.Partido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.AsistEntrenamiento", b =>
                {
                    b.HasOne("GestionEquipo.DB.DATA.ENTITY.Entrenamiento", "Entrenamiento")
                        .WithMany()
                        .HasForeignKey("EntrenamientoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionEquipo.DB.DATA.ENTITY.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenamiento");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("GestionEquipo.DB.DATA.ENTITY.EstPartido", b =>
                {
                    b.HasOne("GestionEquipo.DB.DATA.ENTITY.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionEquipo.DB.DATA.ENTITY.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });
#pragma warning restore 612, 618
        }
    }
}
